### ISSUE TITLE
[BUG] Selecting a time before 10:00 doesn't work

### ISSUE THREAD

**Issue by maltsavkiryl** [stamhoofd/stamhoofd#90] opened 2021-06-03 14:10 UTC
When you try to select a time before `10:00` it automatically clears the input. I assume it fails because timestamps before `10:00` have a leading zero.

https://user-images.githubusercontent.com/12672784/120651565-38564280-c47f-11eb-9a33-4a0830a45dee.mov

**Comment by SimonBackx** [comment] 2021-06-03 16:05
Thank you for the report! I think this bug is caused by a combination of browser specific behaviour (chrome might clear the input box if we set it to an invalid time - because we don't add a leading zero). In the meantime you can try in a different browser (e.g. Safari works).

**Comment by maltsavkiryl** [comment] 2021-06-04 07:15
Confirmed that it works in safari. The time input generally works a lot better in safari than it does in chrome 🥲

**Comment by SimonBackx** [comment] 2021-06-04 14:04
Fixed in the next release 🚀

**Closed by SimonBackx** 2021-06-04 14:04 UTC
Labels: bug
